### ISSUE TITLE
Add more content to website

### ISSUE THREAD

**Issue by mantono** [Sportsektionen/sportsektionen.github.io#1]
- [ ] Våra aktiviteter 
- [ ] Engagera dig i Sporten 
- [ ] Åre SkiWeek 
- [ ] Styrelsen 
- [ ] Hall of Fame 
- [ ] (översättning?)

**Comment by mantono** [comment]
@MissVu Skriv gärna mer utförligt här om det är något mer precist som du tycker ska vara med under respektive kategori.

**Comment by MissVu** [comment]
[website_testdeign.pptx](https://github.com/Sportsektionen/sportsektionen.github.io/files/659405/website_testdeign.pptx)

**Comment by misvu** [comment]
[website_testdeign.pptx](https://github.com/Sportsektionen/sportsektionen.github.io/files/659407/website_testdeign.pptx)

**Comment by mantono** [comment]
Snyggt!

Väldigt konkret, känns som vi har något att jobba med nu. Bra jobbat :)

**Comment by mantono** [comment]
https://www.w3schools.com/howto/howto_html_include.asp

**Comment by mantono** [comment]
https://www.w3schools.com/html/html_lists.asp
